pipeline {
    agent any

    environment {
        NEXUS_URL = 'http://nexus:8081'
        NEXUS_REPOSITORY = 'maven-releases'
        ARTIFACT_GROUP = 'com.example'
        ARTIFACT_ID = 'user-management'
        ARTIFACT_VERSION = '1.1.2'
        ARTIFACT_FILE = 'target/user-management-1.0-SNAPSHOT-shaded.jar'
        NEXUS_CREDENTIALS = 'nexus'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', credentialsId: 'jenkins-github-pat', url: 'https://github.com/Prasadrasal2002/java-app-docker1.git'
            }
        }

        stage('Setup Maven Settings') {
            steps {
                script {
                    sh 'mkdir -p ~/.m2'
                    sh 'cp java/.m2/settings.xml ~/.m2/settings.xml'
                }
            }
        }

        stage('Upload to Nexus') {
            steps {
                dir('java') {
                    script {
                        withCredentials([usernamePassword(credentialsId: "${NEXUS_CREDENTIALS}", usernameVariable: 'NEXUS_USER', passwordVariable: 'NEXUS_PASS')]) {
                            sh """
                            mvn deploy:deploy-file \
                                -Durl=${NEXUS_URL}/repository/${NEXUS_REPOSITORY}/ \
                                -DrepositoryId=nexus \
                                -Dfile=${ARTIFACT_FILE} \
                                -DgroupId=${ARTIFACT_GROUP} \
                                -DartifactId=${ARTIFACT_ID} \
                                -Dversion=${ARTIFACT_VERSION} \
                                -Dpackaging=jar \
                                --settings ~/.m2/settings.xml
                            """
                        }
                    }
                }
            }
        }
    }
}
