pipeline {
    agent any

    tools {
        maven 'maven'  // Ensure Maven is installed via Jenkins tools
    }

    environment {
        NEXUS_URL = 'http://nexus:8081'
        NEXUS_REPOSITORY = 'maven-releases'
        ARTIFACT_GROUP = 'com.example'
        ARTIFACT_ID = 'user-management'
        ARTIFACT_VERSION = '1.1.2'
        ARTIFACT_FILE = 'target/user-management-1.0-SNAPSHOT-shaded.jar'
        NEXUS_CREDENTIALS = 'nexus'
    }

    stages {
        stage('Setup Maven') {
            steps {
                script {
                    sh 'mkdir -p /var/jenkins_home/.m2'
                    sh 'cp java/.m2/settings.xml /var/jenkins_home/.m2/settings.xml'
                }
            }
        }

        stage('Upload to Nexus') {
            steps {
                dir('java') {
                    script {
                        withCredentials([usernamePassword(credentialsId: "${NEXUS_CREDENTIALS}", usernameVariable: 'NEXUS_USER', passwordVariable: 'NEXUS_PASS')]) {
                            sh """
                            mvn deploy:deploy-file \
                                -Durl=${NEXUS_URL}/repository/${NEXUS_REPOSITORY}/ \
                                -DrepositoryId=nexus \
                                -Dfile=${ARTIFACT_FILE} \
                                -DgroupId=${ARTIFACT_GROUP} \
                                -DartifactId=${ARTIFACT_ID} \
                                -Dversion=${ARTIFACT_VERSION} \
                                -Dpackaging=jar \
                                --settings /var/jenkins_home/.m2/settings.xml
                            """
                        }
                    }
                }
            }
        }
    }
}
